url: https://jlorenze.github.io
baseurl: /eat

# Site settings
title: Eat
description: "A simple, ad-free, no-nonsense recipe repository."

# Build settings
markdown: kramdown

# things we want to access for organization
collections:
  recipes:
    output: true
  categories:
    output: true
  methods:
    output: true